[project]
name = 'Public-Transportation-Optimization-Platform'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.route-optimization]
path = 'contracts/route-optimization.clar'
clarity_version = 2
epoch = 2.5

[contracts.vehicle-management]
path = 'contracts/vehicle-management.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
